### ISSUE TITLE
WPF Memory leak (when scrolling through file)

### ISSUE THREAD

**Issue by briman0094** [abbaye/WPFHexEditorControl#10]
If I'm scrolling through a file more than a kilobyte or two long, every time I scroll the view at all (up/down), the memory usage of the program increases steadily and does not decrease. I loaded a 1kb binary file using a Stream into the editor, scrolled to the bottom and back to the top a few times, and the program was using 200 MB of RAM.

**Comment by abbaye** [comment]
For test i made the memory don't up to ~200 MB of RAM.  I tested on 1kb-700MB files

the garbage collector dont clear all unused memory on WPF... I need somes help for that.

**Comment by abbaye** [comment]
Working in it!

Now control (in test project) never use more than ~150mg of ram... on good way

**Comment by haseeb-heaven** [comment]
> Working in it!
> 
> Now control (in test project) never use more than ~150mg of ram... on good way

I Added Hex Editor got **50MB RAM** usage on just idle, on other hand _WinForms_ uses only **10-15MB RAM.**
