### ISSUE TITLE
Maximizing window takes ~2 seconds

### ISSUE THREAD

**Issue by grober82** [abbaye/WpfHexEditorControl#101]
Maximizing window with HexEditor takes ~2 seconds (first time only). Can you make it fast and fluid or is WPF too slow? :D

I think it happens because HexDataStackPanel has 666 child controls.

**Comment by abbaye** [comment]
You can preload byte for full screen at launch and this effect will be visible only when control is loaded...

PreloadByteInEditorMode = PreloadByteInEditor.MaxScreenVisibleLineAtDataLoad

Yes it's because many chips controls but it's for one time only.

**Comment by grober82** [comment]
"PreloadByteInEditorMode" only moves the problem to another point in time. ;)

I think the real solution is to not use that many child controls.

**Comment by grober82** [comment]
@abbaye The problem is in BaseByte constructor:

LoadDictionary("/WPFHexaEditor;component/Resources/Dictionary/ToolTipDictionary.xaml");
Source = FindResource("ByteToolTip");

If I remove it is significantly faster to create the controls. So it is just the tool tip. Maybe it can be optimized.

**Comment by abbaye** [comment]
Nice I check this

Thank for helping :smile:

**Comment by abbaye** [comment]
I have not worked on my hexeditor in past few months. 😅   I think I can optimize the tooltip 💪

**Comment by grober82** [comment]
@abbaye Excellent work! The performance is very good now. 👍 

Maybe this is a small bug in tooltip. Byte is always shown as "0".

![image](https://user-images.githubusercontent.com/3605191/121419329-1e7b9a80-c96c-11eb-803b-e0f4b5586747.png)

**Comment by abbaye** [comment]
Yes it's a little bug... I will correct this soon as possible 😉
