### ISSUE TITLE
Outdated NuGet release

### ISSUE THREAD

**Issue by lmcintyre** [abbaye/WpfHexEditorControl#116]
## Expected Behavior
The NuGet package is the same as the available source code.

## Actual Behavior
The NuGet package is outdated and missing the feature added in #109.

**Comment by abbaye** [comment]
Yes I think the nuget version is outdated because I'm not ready to post the lastest code.

**Comment by lmcintyre** [comment]
Sure thing, thanks for your hex editor control. An update will be appreciated whenever you are able.

**Comment by abbaye** [comment]
Thank for good words 😌

You can use the lastest code on GitHub for your project if you want.

**Comment by Bizarrus** [comment]
Some new infos? Is NuGet currently up to date?

**Comment by myd7349** [comment]
Hi！

It would be great to see a bug fix release for the changes in https://github.com/abbaye/WpfHexEditorControl/pull/134. Otherwise, I’ll have to build the WpfHexEditorControl from source every time I build my project.

**Comment by myd7349** [comment]
Hi！

It would be great to see a bug fix release for the changes in https://github.com/abbaye/WpfHexEditorControl/pull/134.
