### ISSUE TITLE
Data Display Inconsistency Between Custom Control and hexed.it When Loading a Specific Hex File

### ISSUE THREAD

**Issue by AJ-comp** [abbaye/WpfHexEditorControl#139]
Describe the bug
When loading the same file, 7.2.0_softdevice_mbr.hex, the output differs between the custom control and the [hexed.it](https://hexed.it/) hex editor. Specifically, the file content is rendered inconsistently in the custom control compared to the expected data view in hexed.it.

To Reproduce

Open the file 7.2.0_softdevice_mbr.hex in [hexed.it](https://hexed.it/).
Note the rendered hexadecimal content and its alignment.
Load the same file in the custom control.
Compare the outputs and observe the discrepancy in how the data is displayed.
Expected behavior
The file content should be displayed consistently and identically in both the custom control and hexed.it. The hexadecimal representation, formatting, and data alignment must match across tools.

Screenshots
Screenshots have been attached to illustrate the issue:

Screenshot 1:
![image](https://github.com/user-attachments/assets/553aca76-6c86-4f08-8282-481cc8d2dbec)

Screenshot 2:
![image](https://github.com/user-attachments/assets/1bc7c792-1e1b-4f7d-a55b-5e8bd8d0c799)

Desktop
OS: [Windows 11]
Browser: [Microsoft Edge] (for hexed.it)

Thank you for maintaining this project. I appreciate your time and effort in reviewing this issue. Please let me know if additional details or files are required.

[7.2.0_softdevice_no_mbr.zip](https://github.com/user-attachments/files/18048315/7.2.0_softdevice_no_mbr.zip)

**Comment by AJ-comp** [comment]
I have identified the cause of the issue.

There is no problem with the WpfHexEditorControl itself. The difference arises because hexed.it handles .hex files in the Intel Hex format, while WpfHexEditorControl treats them as binary format.

Thank you.

**Comment by abbaye** [comment]
Hi, thank you for precision 😀
