### ISSUE TITLE
Possible to group bytes?

### ISSUE THREAD

**Issue by rikimaru0345** [abbaye/WpfHexEditorControl#15]
Hi,
I want to use the hex editor control to group some bytes into custom groups.
Just like in cheat-engine [Memory View 4byte display mode](https://i.imgur.com/yGpiCVy.png)
For example I have:

`30 17 b5 a2 5d 7c bc b0 ...`

Then I  want to make it so I can group the first 4 bytes and display them as an `Int32`.
(So the first 4 bytes are hidden, and the space they left is filled by one big integer).
I also want to have fine-grained control over what bytes get grouped into what group.
So for example I want to group byte 0-4 into an Int32, and then leave 1 byte as it is, then group 6-7 into a custom display...

I'm experienced with wpf but I'm not sure about the best/intended workflow.
Can you give a rough outline of how one could accomplish this? @abbaye

**Comment by abbaye** [comment]
hi, the control support byte grouping and support showing byte in decimal but I not sure if support exacly that you want. I will check for this after job ;)

**Comment by abbaye** [comment]
I think the best way to make that you want is to fork control and modify to do that ;) all it's possible and hexcontrol are easily modifiable.

**Comment by abbaye** [comment]
you can create a derived Ibytecontrol for make that you want and adapt traverse method to catch them easily. or juste modifies hexbyte.cs for make that you want when it's needed. I think is easy to change that you want

**Comment by rikimaru0345** [comment]
I see, so derive from IByteControl.
Thank you for your input, I will try that and report back :)

**Comment by abbaye** [comment]
good :) regards

**Comment by abbaye** [comment]
i can help you if you want

**Comment by abbaye** [comment]
if you have questions please let me know
