### ISSUE TITLE
How to Save & Application Stop Unexpectedly ?

### ISSUE THREAD

**Issue by KaustubhPatange** [abbaye/WpfHexEditorControl#18]
Sorry, for Disturbing you Again. Actually I have two issues

1. How to Save the Edited Hex File I tried to figure it out, but sample doesn't contain any such example.

2. Whenever I select Fill selection with Byte, it gets stuck and stops.. I have attached a video in zip which will show you how to reproduce the issue.

Thanks Again! Your Work is really Worth 
[attach.zip](https://github.com/abbaye/WpfHexEditorControl/files/1514401/attach.zip)

**Comment by abbaye** [comment]
You can save with SubmitChange() for crash o will check this soon :)

**Comment by abbaye** [comment]
Put your build in Debug and send me a screenshot where the code crash please.

**Comment by abbaye** [comment]
Hi @KaustubhPatange the bug are fixed !  

Take the lastest code to update. :)
