### ISSUE TITLE
Tooltips not showing for Labels in StatusBar

### ISSUE THREAD

**Issue by n00bje** [abbaye/WpfHexEditorControl#20]
## Expected Behavior
Whenever I hover over the 'Position' or 'Byte Count' Label in the StatusBar, I expect the ToolTip to pop up.

## Actual Behavior
BottomRectangle covers these Labels.
![image](https://user-images.githubusercontent.com/6150967/34501105-bfb72bee-f00d-11e7-8f04-6b30a648b45c.png)

## Steps to Reproduce the Problem

  1. Open a file.
  2. Try to hover over the Labels in the StatusBar.

**Comment by abbaye** [comment]
I Will fix this today :) thank for bug report

**Comment by abbaye** [comment]
Hi n00bje,

Fixed 👍 check picture.

![image](https://user-images.githubusercontent.com/17101371/34505364-cb86ddf4-eff2-11e7-8a29-336c3740f403.png)

Thank for help
