### ISSUE TITLE
Stream Binding not Displaying Data

### ISSUE THREAD

**Issue by Aleksbgbg** [abbaye/WpfHexEditorControl#26]
## Platform
I am using WpfHexEditor in WPF with MVVM.

## Problem
I am using a ViewModel with the following data:
```cs
public MemoryStream Data { get; } = new MemoryStream();

public void Initialise(byte[] data)
{
    Data.Write(data, 0, data.Length);
}
```

I am binding the `MemoryStream` (`Data`) using the following XAML code:
```xaml
<WpfHexEditor:HexEditor Stream="{Binding Data, Mode=OneTime}"/>
```

## Result
This yields an empty editor control:
http://prntscr.com/iksyy4

## Question
The stream binding does not work. The stream only works if set from code-behind.

Do you have a solution to this?

**Comment by abbaye** [comment]
Stream property are not dependency property...

if you need it i can change that

**Comment by abbaye** [comment]
i will check this at end of day.

**Comment by Aleksbgbg** [comment]
Yeah, please make it a `DependencyProperty`. Thanks.

**Comment by abbaye** [comment]
Yes sorry... for this.

It`s work good with file name but never tested ad DP with Stream

**Comment by abbaye** [comment]
i will check this later today

**Comment by Aleksbgbg** [comment]
Okay, let me know when you find the problem.

If you would like, I could make the changes myself.

Thanks.

**Comment by Aleksbgbg** [comment]
Hi, have you looked into the issue yet? Do you know where the problem is?

**Comment by abbaye** [comment]
Hi, 

i it's work for me. are you set your stream in Datacontext ?

**Comment by Aleksbgbg** [comment]
Yes, the DataContext is automatically set by my MVVM framework (Caliburn.Micro).

Could you upload the project where it worked, so I can see if I have done anything wrong? Thanks.

**Comment by abbaye** [comment]
Do you have test your stream directly in code ?

The binding with filename or stream are not two-way but oneway.  You need to call submitchanges() for change data into stream

**Comment by abbaye** [comment]
Are you using the wpfhexeditor or experimental drawedhexeditor for mvvm ?

**Comment by abbaye** [comment]
I'm not using mvvm pattern. But my friend janus can help you.

**Comment by Aleksbgbg** [comment]
I use regular WpfHexEditor (not DrawedHexEditor). I'm not changing the data on the stream, I am only just setting it at the start of the program.

**Comment by JanusTida** [comment]
Testing mail, hello to Alexbgbg.

**Comment by Aleksbgbg** [comment]
Hi @JanusTida

**Comment by JanusTida** [comment]
OK. Could you please send your view model code to me?

**Comment by JanusTida** [comment]
@Alexbgbg

**Comment by JanusTida** [comment]
@Aleksbgbg

**Comment by Aleksbgbg** [comment]
I will upload it to GitHub in a few seconds.

**Comment by JanusTida** [comment]
Ok.

**Comment by Aleksbgbg** [comment]
I uploaded a test project here: https://github.com/Aleksbgbg/HexEditorTest

You can find the UI (View) here: https://github.com/Aleksbgbg/HexEditorTest/blob/master/HexEditorTest/Views/HexEditorView.xaml

You can find the ViewModel here: https://github.com/Aleksbgbg/HexEditorTest/blob/master/HexEditorTest/ViewModels/HexEditorViewModel.cs

The HexEditorViewModel is initialised in MainViewModel: https://github.com/Aleksbgbg/HexEditorTest/blob/master/HexEditorTest/ViewModels/MainViewModel.cs#L11

**Comment by Aleksbgbg** [comment]
Hi @JanusTida,

have you managed to take a look? Found anything problematic? 🤔

**Comment by JanusTida** [comment]
@Aleksbgbg em, this is bug of the control that will be fixed soon. 😉

**Comment by Aleksbgbg** [comment]
@JanusTida thanks Janus.

If you would like, I could fix it myself. If you describe the issue, I can take a look.

**Comment by JanusTida** [comment]
@Aleksbgbg you could try to remove the sentence from the constructor of the control, by which the data context is the set to the control, a is saying from abbaye, please note that removing this sentence may take some effects to the other parts that depend on this word of three control,like status bar.

**Comment by Aleksbgbg** [comment]
Hi @JanusTida,

I have looked through and cannot find any way to solve the problem. I will leave this one to you.

Have you made any progress?

**Comment by JanusTida** [comment]
@Aleksbgbg Hi,I've just made a little fixing to the control,Plz pull the master-branch now,see MVVM-sample-NET47 sample project that demonstrating binding works :)

**Comment by Drachenkaetzchen** [comment]
Hi, I'm having a very similar issue using WPFHexaEditor 1.3.6.2 (can't use 1.4 due to the 4.7 requirement)

I think the problem here is scoping. Here's what I get:

```
System.Windows.Data Error: 40 : BindingExpression path error: 'PluginChunk' property not found on 'object' ''HexEditor' (Name='PluginChunkControl')'. BindingExpression:Path=PluginChunk; DataItem='HexEditor' (Name='PluginChunkControl'); target element is 'HexEditor' (Name='PluginChunkControl'); target property is 'Stream' (type 'MemoryStream')
```

Note that it says that "PluginChunk" (the binding I use) is not found on '''HexEditor''' but should in reality be relative to my ViewModel.

I suspect it's because the DataContext is overridden in the constructor. Unfortunately the sources for 1.3.6.2 don't seem to live on GitHub, so I can only check in the disassembly.

**Comment by abbaye** [comment]
Hi drachen 

You can you the new version of you complied code in 4.5. juste select the good configuration for compile in 4.5

In code source you have sample for all version :)

The project support also 4.5 and 4.7.

**Comment by MrCzz** [comment]
Hello Abbaye,

I do have a problem with the databinding of Stream Property. If I bind a MemoryStream to the Stream-property the data, on which I bind, isn't shown inside the hexeditor.

XAML File:
```csharp
<control:HexEditor
                    Width="Auto"
                    MinHeight="100"
                    MaxHeight="200"
                    Margin="0, 10, 0, 0"
                    AllowExtend="True"
                    AppendNeedConfirmation="False"
                    Stream="{Binding DataStream}" />
```

ViewModel:
```csharp
public ViewModel()
        {           
            DataStream.WriteByte(0x00);           
        }

<--- ... -->

public MemoryStream DataStream { get; }
            = new MemoryStream();
```

I expect that the HexEditor will show me a HexEditor with the data 00 in it, but the HexEditor won't show anything at all.

Could you please have a look at the data binding on Stream? I think it is broken. Tested this on the 1.6.3 release on Nuget on .Net Framework 4.6.1.

If I go through your examples it shows that the Databinding on a DrawedHexEditor is working correctly, so I tried to change the XAML to:

```csharp
<control:DrawedHexEditor
                    Width="Auto"
                    MinHeight="100"
                    MaxHeight="200"
                    Margin="0, 10, 0, 0"
                    Stream="{Binding DataStream}" />
```

Now the databinding correctly works and it shows 00 in the view of the HexEditor, but the DrawedHexEditor doesn't support extending, so the DrawedHexEditor is useless for me a.t.m. 

Do you have a solution for the databinding?

Thank you in advance,
Maurice

**Comment by abbaye** [comment]
Hello Mr

You can't bind stream. 

Check in sample solution how use stream in FindWindow ;)

**Comment by MrCzz** [comment]
Can you point me to the correct example?

Because the .MVVM examples all uses the DrawedHexEditor, which I can't use, and the normal examples don't use any kind of bindings, but in MVVM you can't direct navigate to the HexEditor.

MVVM Examples: https://github.com/abbaye/WpfHexEditorControl/tree/master/WpfHexEditor.Sample.MVVM/Shell (Only using DrawedHexEditor)
Non-MVVM Example: https://github.com/abbaye/WpfHexEditorControl/tree/master/WPFHexaEditorExample (Because it is a partial class you can navigate to the Hexeditor by giving it a name, but this isn't possible in MVVM)

**Comment by abbaye** [comment]
Don't use the mvvm sample beacase is another hexeditor in development by Janus Tida (great work but in alpha stage)

Use normal sample

**Comment by abbaye** [comment]
Use sample

Non-MVVM Example: https://github.com/abbaye/WpfHexEditorControl/tree/master/WPFHexaEditorExample

Check FindReplaceDialog

You CAN'T bind directly a stream. For now you need to pass by code.

When I will have more time I will work on stream binding (I have just put 2-3hrs of work on stream in project)

**Comment by mail278** [comment]
Hi,
as few people mentioned, problem is that you override datacontext of HexEditor control. So if I bind to my VM, you immediately change the datacontext and the binding is broken.

There are few workarounds how to fix this (one is probably to bind to parent control datacontext).

I used this one, because I also want to send copy of MemoryStream to HexEditor.
You need to create attached property which
1. creates copy of MemoryStream
2. sets it to Stream property
3. this attached property must be set somewhere abowe HexEditor (not directly), so it does not relay on HexEditor's datacontext.

BindStream.cs

```
 public class BindStream : DependencyObject
  {
    public static readonly DependencyProperty StreamBindingProperty = DependencyProperty.RegisterAttached(
      "StreamBinding",
      typeof(MemoryStream),
      typeof(BindStream),
      new FrameworkPropertyMetadata(null, OnStreamBindingChanged)
    );


    private static void OnStreamBindingChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
      var hexEditor = d.FindChildByType<HexEditor>();
      
      if (hexEditor != null) hexEditor.Stream = CopyStream(e.NewValue as MemoryStream);
    }

    public static void SetStreamBinding(DependencyObject d, MemoryStream value)
    {
      d.SetValue(StreamBindingProperty, value);
    }
    public static Stream GetStreamBinding(DependencyObject d)
    {
      return (MemoryStream)d.GetValue(StreamBindingProperty);
    }

    private static MemoryStream CopyStream(MemoryStream original)
    {
      if (original == null) return null;

      var ms = new MemoryStream();
      original.Position = 0;
      original.CopyTo(ms);
      ms.Position = 0;
      return ms;
    }
```

XAML
```
<Grid behaviors:BindStream.StreamBinding="{Binding RawData}">
<wpfHexaEditor:HexEditor />
</Grid>
```

**Comment by abbaye** [comment]
Hi @mail278 

i will check this, Sorry i have missed your post
