### ISSUE TITLE
Different languages in designer and executed application

### ISSUE THREAD

**Issue by Guddiny** [abbaye/WpfHexEditorControl#27]
## Expected Behavior
Same languages

## Actual Behavior
Different languages

## Steps to Reproduce the Problem

  1. VS 2017 English lang.
  2. System (Windows 7 x64 sp3) - system lang. - russian
  3. Add control to WPF app.
![issue_pic](https://user-images.githubusercontent.com/16209082/37240062-762754b6-244e-11e8-8fc7-5e3a7f19febd.PNG)

**Comment by abbaye** [comment]
Wpf localization use system language (normally) not vs language.  What is your system codepage language ?

**Comment by Guddiny** [comment]
Russian. 
So i try to set Language property to "en-US"  but it doesn't work

**Comment by abbaye** [comment]
You can force control in constructor by adding a line of code before initialisecomponent()

**Comment by abbaye** [comment]
Or delete Russian language in solution
