### ISSUE TITLE
Standalone application?

### ISSUE THREAD

**Issue by Sanqui** [abbaye/WpfHexEditorControl#28]
From the screenshots, WPFHexaEditor looks great.  Is there a standalone application using it, like a general purpose hex editor?

**Comment by abbaye** [comment]
From now it's only a components  for using in apps. In future I want to make complete apps for it

**Comment by Sanqui** [comment]
I'm excited :)

**Comment by abbaye** [comment]
Before working on it I want work on file format detector with for visual view of file format (with background color, tooltip etc...)

**Comment by abbaye** [comment]
Fow now i'm plan to only make a good user control.

I think do have the time to make a complete stand alone app.
