### ISSUE TITLE
Spelling issue for Length in HexBox

### ISSUE THREAD

**Issue by Mgamerz** [abbaye/WpfHexEditorControl#29]
## Expected Behavior
 - Length is spelled correctly

## Actual Behavior
 - It is not.

## Steps to Reproduce the Problem

  1. See picture below, created by adding a control:HexBox to my window.
![image](https://user-images.githubusercontent.com/2738836/39392029-ea016966-4a6a-11e8-8082-3c9708c798ef.png)

It should be spelled **Length**.

**Comment by abbaye** [comment]
I will fix it soon :) thank you

**Comment by Mgamerz** [comment]
Thanks. I am starting to use this in one of my upcoming projects as we move from winforms to WPF.

**Comment by abbaye** [comment]
done,

Thank you :)
