### ISSUE TITLE
Add character table support

### ISSUE THREAD

**Issue by vector-man** [abbaye/WPFHexEditorControl#3]
It would be nice if character tables could be loaded. More information here: https://tcrf.net/Hex_editor

**Comment by abbaye** [comment]
yes I know that!!! when I am young I have created Ultimate hacking Rom and
Visual Rom Suite and a VRS thingy like tool. :)

Sorry this reminds me of youthful memories

But with a lot of code It's is possible to load TBL file. I just need to
work a lot :)

It's that you need ?


Best regards

Le 17 févr. 2017 17:51, "Michael D. Corbett" <notifications@github.com> a
écrit :

**Comment by abbaye** [comment]
I have started implementation of TBL file.
Code from my project Visual Rom Suite.
:)


Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.
-------- Message d'origine --------De : Derek Tremblay <derektremblay666@gmail.com> Date : 17-02-17  19:50  (GMT-05:00) À : abbaye/WPFHexEditorControl <reply@reply.github.com> Cc : Subscribed <subscribed@noreply.github.com>, j abbaye/WPFHexEditorControl <WPFHexEditorControl@noreply.github.com> Objet : Re: [abbaye/WPFHexEditorControl] Add character table support (#3) 
 yes I know that!!! when I am young I have created Ultimate hacking Rom and Visual Rom Suite and a VRS thingy like tool. :)
Sorry this reminds me of youthful memories

But with a lot of code It's is possible to load TBL file. I just need to work a lot :) 
It's that you need ?

Best regards 
Le 17 févr. 2017 17:51, "Michael D. Corbett" <notifications@github.com> a écrit :
It would be nice if character tables could be loaded. More information here: https://tcrf.net/Hex_editor

**Comment by vector-man** [comment]
Wow, thank you! I also used to work on a lot of ROM tools (and am planning some in the future). My most popular one was SBWin converter :).

**Comment by abbaye** [comment]
Good !! I think a can make a usable version shortly



Le 18 févr. 2017 21:57, "Michael D. Corbett" <notifications@github.com> a
écrit :

**Comment by abbaye** [comment]
You can load TBL file now 
This afternoon I will check for coloring DTE/MTE and resize at content.


Envoyé de mon appareil Samsung de Bell via le réseau le plus vaste au pays.
-------- Message d'origine --------De : Derek Tremblay <derektremblay666@gmail.com> Date : 17-02-19  07:28  (GMT-05:00) À : abbaye/WPFHexEditorControl <reply@reply.github.com> Cc : Comment <comment@noreply.github.com>, abbaye/WPFHexEditorControl <WPFHexEditorControl@noreply.github.com> Objet : Re: [abbaye/WPFHexEditorControl] Add character table support (#3) 
Good !! I think a can make a usable version shortly 


Le 18 févr. 2017 21:57, "Michael D. Corbett" <notifications@github.com> a écrit :
Wow, thank you! I also used to work on a lot of ROM tools (and am planning some in the future). My most popular one was SBWin converter :).

**Comment by abbaye** [comment]
I will check your tool :)
