### ISSUE TITLE
Typing shifted characters extends selection

### ISSUE THREAD

**Issue by pm64** [abbaye/WpfHexEditorControl#33]
## Expected Behavior
Bytes are replaced without creating/extending selection.

## Actual Behavior
Selection extends to new cursor position

## Steps to Reproduce the Problem

  1. Load binary data into control
  2. On the ASCII side, replace byte with character that is upper-case or otherwise requires holding down the Shift key for entry
  3. Observe selected area

The issue seems to center around HexaEditor.xaml.cs in Control_MoveRight() around line 1210.

**Comment by abbaye** [comment]
I Will check this soon as possible :) Thank you

**Comment by abbaye** [comment]
I can't reproduce bug.

can you sput a screenshot ?

**Comment by abbaye** [comment]
FIXED... sorry for delay
