### ISSUE TITLE
nuget installation error

### ISSUE THREAD

**Issue by darkleem** [abbaye/WpfHexEditorControl#34]
## Expected Behavior
Installation should be completed without problem.

## Actual Behavior
There is an error that can not be installed in that version.

## Steps to Reproduce the Problem

1. . NET Framework 4.5. Create a project in X version.
2. We install WpfHexEditorControl 1.4 Version through Nuget Manager.

Version 1.3.6.2 seems to be installed correctly, so it seems that the .NET Framwork Version is fixed at 4.7 in Nuget Package.

**Comment by darkleem** [comment]
Why does not 4.5 support?
nuget can support multiple versions.

**Comment by abbaye** [comment]
Code version on GitHub support 4.5 and 4.7. nuget version 1.4.0 support only 4.7 and version 1.2.1 support 4.5

**Comment by abbaye** [comment]
Now nuget package support 4.5.1 and 4.7 framework
