### ISSUE TITLE
Change Display Offset

### ISSUE THREAD

**Issue by vector-man** [abbaye/WpfHexEditorControl#38]
## Expected Behavior
I would like the ability to change the starting offset (0x1) displayed to a custom value.  I'm trying to recreate the hex control behavior as shown in my application in this screenshot: https://www.romhacking.net/forum/index.php?topic=17693.0

## Actual Behavior
Offset seems to only start in the editor with 0x1. Not sure which property would allow me to change the starting offset displayed.

## Steps to Reproduce the Problem

  1. Load data into the hex editor and you'll see 0x1 at the start of the data.

**Comment by abbaye** [comment]
Yes use ByteShiftLeft property. I think should be helping tou

**Comment by vector-man** [comment]
It works well under certain circumstances, but when I change the stream data (dispose the stream and reload a MemoryStream of bytes), it seems to make the display of the addresses disappear altogether.

**Comment by vector-man** [comment]
I think I was doing it wrong. Will try again today and let you know.

**Comment by vector-man** [comment]
Yeah, when I use ByteShiftLeft, close the provider and dispose of the stream, then  set a new stream and attemptto use ByteShiftLeft again, all addresses displayed on the left disappear.

**Comment by JanusTida** [comment]
> 
> ## Expected Behavior
> 
> I would like the ability to change the starting offset (0x1) displayed to a custom value. I'm trying to recreate the hex control behavior as shown in my application in this screenshot: https://www.romhacking.net/forum/index.php?topic=17693.0
> ## Actual Behavior
> 
> Offset seems to only start in the editor with 0x1. Not sure which property would allow me to change the starting offset displayed.
> ## Steps to Reproduce the Problem
> 
>     1. Load data into the hex editor and you'll see 0x1 at the start of the data.

Hey Mr,you may consider implementing a Stream that starts from the specified offset and end until it reaches the specified length.and bind it to the StreamProperty of DrawedHexEditor,the sample implemention is [https://github.com/JanusTida/CDFC.Common/blob/master/CDFC.Util/IO/MulPeriodsStream.cs](url)

**Comment by abbaye** [comment]
Yes it's not a problems to implement that's soon

**Comment by abbaye** [comment]
I'm working on that. I will implement 2 property for set what you want to shown in control. The byte provider will load all the stream anyway and you will dont lost your work. if you set to -1 the control will be return to normal.

VisualStartByteAdress
VisualStopByteAdress or Lenght ?? (is better to set stop address or lenght from start ?)

It's work in progress, i will check-in when is stable.

Please send to your sugestion:

**Comment by abbaye** [comment]
first checkin but you can find the base property. I will implementing this week :)

**Comment by abbaye** [comment]
it's work at about 50%...

it's need a lot of modification in control for work perfectly.

**Comment by abbaye** [comment]
Hi @vector-man !!

I think what you wanted work fine.

I think some little bug need to be corrected (probably this weekend)
- Control up, down, ..., page up, page down... not valid th focus when reach the first/max position you needed to show
- the column number dont hightlight the good column

If you can please check and come back to me. 

Best regards
