### ISSUE TITLE
Multiple Highlights Support?

### ISSUE THREAD

**Issue by vector-man** [abbaye/WpfHexEditorControl#39]
I would like support for multiple highlights that can be added and removed, of varying colors.

Something like:

hexView.Highlights.Add(offset, length, color);

As well as 
hexView.Highlights.RemoveAt(...) 

And the rest of the functionality supported by collections.

Is this supported in any way currently?

If not, if you are still busy, I'll try to add it and send a pull request :).

**Comment by abbaye** [comment]
I'm already started to work on that but not time.to compete now

You can try and send to me a pull request :)

**Comment by abbaye** [comment]
I'm working on CustomBackGroundBlock functionality. I will try to complete before summer

**Comment by abbaye** [comment]
You can check code on master branch

**Comment by abbaye** [comment]
I @vector-man  do you still need this feature ?

**Comment by abbaye** [comment]
I think it's completed

Use these methods:
- AddHighLight()
- RemoveHighLight()
