### ISSUE TITLE
Backspace from position 0 causes infinite loop 

### ISSUE THREAD

**Issue by Dimitrisvech** [abbaye/WPFHexEditorControl#4]
Need to add validation that the position in file is not negative.
file: HexaEditor.xaml.cs
line 2256:
```csharp
if (bytePositionInFile >= _provider.Length || bytePositionInFile < 0)
```

line 2289:
```csharp
if (bytePositionInFile >= _provider.Length || bytePositionInFile < 0)
```

**Comment by abbaye** [comment]
Thanks you for this issue. I will add this validation today :)

**Comment by abbaye** [comment]
after testing i modified UserControl_KeyDown on StringByteControl.xaml.ca and hexByteControl.xaml.ca 

....
                    **if (BytePositionInFile > 0)**
                        MovePrevious?.Invoke(this, new EventArgs());
....

Thank for this issue :)

Test this please.
