### ISSUE TITLE
Misconstructed dependency property in HexDataLayer.cs

### ISSUE THREAD

**Issue by chostelet** [abbaye/WpfHexEditorControl#40]
## Expected Behavior
At line 308 in HexDataLayer.cs the registered name should be  <b>HexForegroundPositions</b>                                  

## Actual Behavior
At line 308 in HexDataLayer.cs the registered name is currently <b>HexForegroundPositionsProperty</b>

**Comment by JanusTida** [comment]
Thanks for correcting,the registered name is now fixed.:),by the way I haved added the hilighting capability for FAT32(if you have a fat32 raw img file) and Executable files to Master branch(See ExeStreamToSeagmentParser and FatStreamToSeagmentParser in Shell Demo project,and I used MEF as my IOC container.) this capability shows how CustomForegroundBlocks and CustomBackgroundBlocks work in DrawedHexEditor :).

**Comment by chostelet** [comment]
Would like to check this, however I'm using VS2017 Enterprise and I'm getting too many errors when trying to open/build the whole solution. Have to ignore most of the projects.
Errors are:
 - Migration : WpfHexEditor.UnitTest - incompatible with VS2017 (unknown reason)
 - Opening with Blend  =>  NuGet packages - most are outdated (CommonServiceLocator, Prism, System.ValueTuple, …). Not easy to repair/amend for a dummy like me..

However should have a look at this really neat work (even if not using Prism).

**Comment by JanusTida** [comment]
I've checked the solution as you described,but I've just got only one incompatible error loading the UnitTest project while opening it with Blend 2017,(even I've cloned the whole repository),as I know,blend can't load unit test project,so this can't be a problem.but I haven't got these complie error as you decribed,all the things work well on VS2017 in both repositories.I have some suggestions for you problems.
  1.You could to right click the unittest project,choose reload project,if the error keeps there,you may need to check if your Visual Studio need Unit Test Components setuped.
  2.Right click the solution and choose restore nuget packages.and System.ValueTuple is now upgrated to the latest version,but the latest Prism(7.1) version removed the MEF feature supported,which I used in my DEMO project,so the Old Prism(6.3) still be referenced.

**Comment by chostelet** [comment]
Hi,

 

Issues solved.

 

I switched back to VS2017 (instead of Blend), reloaded the unit test project, used NuGet to add the MSTest Framework (it was missing).

 

In addition, I had to set VS to allow only one compile at time (no parallel compilation).

 

Should be allowed to play now :)

--

Christian HOSTELET - Grenoble

 

De : JanusTida <notifications@github.com> 
Envoyé : mardi 2 avril 2019 15:51
À : abbaye/WpfHexEditorControl <WpfHexEditorControl@noreply.github.com>
Cc : Christian Hostelet <christian.hostelet@free.fr>; Author <author@noreply.github.com>
Objet : Re: [abbaye/WpfHexEditorControl] Misconstructed dependency property in HexDataLayer.cs (#40)

 

I've checked the solution as you described,but I've just got only one incompatible error loading the UnitTest project while opening it with Blend 2017,(even I've cloned the whole repository),as I know,blend can't load unit test project,so this can't be a problem.but I haven't got these complie error as you decribed,all the things work well on VS2017 in both repositories.I have some suggestions for you problems.
1.You could to right click the unittest project,choose reload project,if the error keeps there,you may need to check if your Visual Studio need Unit Test Components setuped.
2.Right click the solution and choose restore nuget packages.and System.ValueTuple is now upgrated to the latest version,but the latest Prism(7.1) version removed the MEF feature supported,which I used in my DEMO project,so the Old Prism(6.3) still be referenced.

**Comment by chostelet** [comment]
Hi Janus,

 

Just to be more precise on what helps solved the various issues.

 

Using NuGet manager, I used the restore, however after that action, I had to (re-)install the following NuGet items:

*	CommonServiceLocator v1.3.0 (instead of latest v2.0.4) for MVVM projects
*	MSTest.TestFrameword and MSTest.TestAdapter v1.2.0 (instead of latest v1.4.0) for Test project
*	Prism.Core, Prism.Wpf v6.3.0 (instead of latest v7.1.0.431) for MVVM projects (per your remark below on MEF)
*	System.ValueTuple v4.5.0 for most of projects – however I suspect for NET47 it is useless.

 

I setup all projects’ properties to use the latest minor version of C# compiler.

 

I also had set the “maximum number of parallel projects builds” to 1 in Tools -> Options -> Projects and Solutions -> Build and Run.

 

And finally, I ran successfully the few tests after modifying the filename used for GetByteCountTest.

 

Regards

--

Christian HOSTELET - Grenoble

 

De : Christian HOSTELET <christian.hostelet@free.fr> 
Envoyé : mardi 2 avril 2019 17:49
À : 'abbaye/WpfHexEditorControl' <reply@reply.github.com>; 'abbaye/WpfHexEditorControl' <WpfHexEditorControl@noreply.github.com>
Cc : 'Author' <author@noreply.github.com>
Objet : RE: [abbaye/WpfHexEditorControl] Misconstructed dependency property in HexDataLayer.cs (#40)

 

Hi,

 

Issues solved.

 

I switched back to VS2017 (instead of Blend), reloaded the unit test project, used NuGet to add the MSTest Framework (it was missing).

 

In addition, I had to set VS to allow only one compile at time (no parallel compilation).

 

Should be allowed to play now :)

--

Christian HOSTELET - Grenoble

 

De : JanusTida <notifications@github.com <mailto:notifications@github.com> > 
Envoyé : mardi 2 avril 2019 15:51
À : abbaye/WpfHexEditorControl <WpfHexEditorControl@noreply.github.com <mailto:WpfHexEditorControl@noreply.github.com> >
Cc : Christian Hostelet <christian.hostelet@free.fr <mailto:christian.hostelet@free.fr> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Objet : Re: [abbaye/WpfHexEditorControl] Misconstructed dependency property in HexDataLayer.cs (#40)

 

I've checked the solution as you described,but I've just got only one incompatible error loading the UnitTest project while opening it with Blend 2017,(even I've cloned the whole repository),as I know,blend can't load unit test project,so this can't be a problem.but I haven't got these complie error as you decribed,all the things work well on VS2017 in both repositories.I have some suggestions for you problems.
1.You could to right click the unittest project,choose reload project,if the error keeps there,you may need to check if your Visual Studio need Unit Test Components setuped.
2.Right click the solution and choose restore nuget packages.and System.ValueTuple is now upgrated to the latest version,but the latest Prism(7.1) version removed the MEF feature supported,which I used in my DEMO project,so the Old Prism(6.3) still be referenced.

**Comment by JanusTida** [comment]
#closed
