### ISSUE TITLE
Potential wrong GetSelectionLength method in ByteProvider.cs ?

### ISSUE THREAD

**Issue by chostelet** [abbaye/WpfHexEditorControl#41]
In ByteProvider.cs / GetSelectionLength() method (line #692) the test for no selection seems incorrect.

It is:
 `if (selectionStop == -1 || selectionStop == -1) …`

Shouldn't it be ?
"_if (**selectionStart** == -1 || selectionStop == -1)_ ..."

**Comment by chostelet** [comment]
Same remark for GetCopyData method (line #738) in ByteProvider.cs

**Comment by abbaye** [comment]
Hi chostlet

This work fine. 

You can propose better check ? :) If yes I will change methods :)

Best regards

**Comment by chostelet** [comment]
Hello Derek,

Just wondering why checking 2 times in a logical OR the same parameter (selectionStop)...

**Comment by chostelet** [comment]
Hello Derek,

Seen no reply on this.
You're suggesting me to propose a better check… :-)

Why not : if ((selectionStart == -1) || (slectionStop == -1))

instead of :  if ((selectionStop == -1) || (slectionStop == -1))
as it is currently in the master branch.

**Comment by abbaye** [comment]
Lolll I have just seen the bug ... 2time check on selectionStop... 

You have totally reason :)

I will make the changes this weekend! Thank you mister!

**Comment by chostelet** [comment]
And probably you can hit two birds with a stone ("d'une pierre, deux-coups") looking at issue #42  :-)

**Comment by abbaye** [comment]
Je suis français (Québec) ;)

**Comment by chostelet** [comment]
Je m'en doutais :-)
Indices: dans quelques fichiers source, des petits commentaires en français… :)

**Comment by abbaye** [comment]
Héhé oui les fichiers de TBL on été fait en 2003 et je les avais commenté en français. :)

**Comment by abbaye** [comment]
Je vais faire les correctifs que tu m'a proposé ce matin

**Comment by abbaye** [comment]
Corrigé!

**Comment by chostelet** [comment]
Super !

 

Je continue d’explorer ta réalisation qui, je dois le dire, est rare.

 

--

Christian HOSTELET - Grenoble

 

De : Derek Tremblay <notifications@github.com> 
Envoyé : samedi 13 avril 2019 13:39
À : abbaye/WpfHexEditorControl <WpfHexEditorControl@noreply.github.com>
Cc : Christian Hostelet <christian.hostelet@free.fr>; Author <author@noreply.github.com>
Objet : Re: [abbaye/WpfHexEditorControl] Potential wrong GetSelectionLength method in ByteProvider.cs ? (#41)

 

Corrigé!

**Comment by abbaye** [comment]
Merci!!!! J'ai fais ça pour le plaisir ;)

Si tu veux une petit étoiles sur le projet serait apprécié :smiley:

**Comment by chostelet** [comment]
Aussitôt fait :)

 

 

 

--

Christian HOSTELET - Grenoble

 

De : Derek Tremblay <notifications@github.com> 
Envoyé : samedi 13 avril 2019 16:31
À : abbaye/WpfHexEditorControl <WpfHexEditorControl@noreply.github.com>
Cc : Christian Hostelet <christian.hostelet@free.fr>; Author <author@noreply.github.com>
Objet : Re: [abbaye/WpfHexEditorControl] Potential wrong GetSelectionLength method in ByteProvider.cs ? (#41)

 

Merci!!!! J'ai fais ça pour le plaisir ;)

Si tu veux une petit étoiles sur le projet serait apprécié 😃

**Comment by abbaye** [comment]
Merci !

**Comment by abbaye** [comment]
Je t'ai ajouté dans ma liste de follow :)
