### ISSUE TITLE
Potentially wrong CaretWidth property implementation in Caret.cs

### ISSUE THREAD

**Issue by chostelet** [abbaye/WpfHexEditorControl#42]
Hi,

In 'Caret.cs' line 114, the set value is compared to '_caretHeight' field instead of '_caretWidth' field.
Some OnPropertyChanged events may not be fired.
This also may trigger false/unnecessary OnPropertyChanged events.

**Comment by abbaye** [comment]
Thank you I will correct this soon :)

**Comment by abbaye** [comment]
Corrected :) Thank you
