### ISSUE TITLE
Is there a plan to develop for the replace function?

### ISSUE THREAD

**Issue by philipxyc** [abbaye/WpfHexEditorControl#43]
I've noticed that an "Find and replace" menu has been added to the sample. However, all those replace button do not have a related backend logic. I've tried to implement this function but failed, because there are too many code needed to review. 

So, I'm wondering that Is there a plan to develop for the replace function? Or maybe you could provide the possible code structure for this function, then I could try to work on it and make a pr.

**Comment by abbaye** [comment]
I plan to implement this soon. 

I'm working on Issue #38 and after that I will can work on find replace :)

**Comment by philipxyc** [comment]
Got it! Thanks!

**Comment by abbaye** [comment]
hi @philipxyc 

I will work on replace bytes backend methods.

It will be possible to replace the a bytes array by another of identical length. if the length is bigger than original the array will be trim by the right.

**Comment by abbaye** [comment]
Hi @philipxyc 

I have completed all backend logic of Replace fonction (ReplaceFirst, ReplaceNext, ReplaceAll) and multiple overload. I will work on sample project for implement it on the UI FindReplaceDialog ...

Best regards

**Comment by abbaye** [comment]
I think it's completed.

if you see anything post me and i will reopen this issue :)
