### ISSUE TITLE
Show line instead of position

### ISSUE THREAD

**Issue by PersianEngineer** [abbaye/WpfHexEditorControl#44]
Is there any way to show number of line instead of position in left side of hex editor?
like this:
https://imgur.com/UBviXQp
Thanks

**Comment by abbaye** [comment]
Actually no you are the first request for this.

But it's very easy to implement :) I can do that soon I you need that

**Comment by PersianEngineer** [comment]
Hi,
It would be great if you do that for me. I needed that in this great control.
Can you show me changes? Because I've made some change in control.
Thank you <3

**Comment by abbaye** [comment]
I will put a commit soon a possible for you. And you can see the change on this issue :smile:

**Comment by PersianEngineer** [comment]
Thank you so much. I'll wait then. <3

**Comment by abbaye** [comment]
I will add these posibility for position panel
- Show position Hex or decimal
- Show line number Hex or Decimal 
- Show positon and line...

it's ok for you ?

**Comment by PersianEngineer** [comment]
Hi,
Yes, that will do the job great.
Thanks

**Comment by abbaye** [comment]
I will add a properties for control that you want to show

**Comment by abbaye** [comment]
Hi @PersianEngineer !

test what you have requested with OffSetPanelPanelVisual property... You have 3 modes (LineOnly,  OffsetOnly and Both)

Please give me a feedback

Regards

**Comment by abbaye** [comment]
I will optimize my code tommorow. I have made this change in 15-30min but not optimize them lol 🤦‍♂️

**Comment by PersianEngineer** [comment]
Thank you. that's what i want. 
You did great work. <3

**Comment by abbaye** [comment]
Best regards!

I will work soon on your other issue
