### ISSUE TITLE
Get and Set change in editor via code

### ISSUE THREAD

**Issue by PersianEngineer** [abbaye/WpfHexEditorControl#46]
Hello,
Is there any way to get and set changes via code and be able to save all bytes to a new file?
I'd tried GetAllBytes function but it only gives me zero byte or changed bytes!
Please help me about this.
Tnx <3

**Comment by abbaye** [comment]
It's possible to make that via code

Check public properties/methods :smile:

**Comment by abbaye** [comment]
I think I will have somes times this night to more help you.

Sorry I'm in traveling but I will go at home today 

Best regards

**Comment by dondrakon** [comment]
Hello @PersianEngineer 

You can try to use this workaround:

 ```
 hexEditor.ReplaceByte(0, 1, 0x3C, 0x00); // Replasing the first byte in my test file
 hexEditor.UpdateVisual();
  hexEditor.SelectAll(); //It is nessesary to correct work of GetAllBytes method
  byte[] bytes = hexEditor.GetAllBytes(); // The method returns all bytes from editor to the array
  hexEditor.UnSelectAll();
```

**Comment by abbaye** [comment]
Normally getallbytes work fine

Put some code please

**Comment by abbaye** [comment]
@PersianEnginner do you use a memorystream or file in the editor ??
