### ISSUE TITLE
Open file take a while at first load!

### ISSUE THREAD

**Issue by PersianEngineer** [abbaye/WpfHexEditorControl#47]
Hello mr abbaye,
I hope you are fine.
I don't know that this is an issue or what, but I have an issue while using editor to show bytes.
At first open file, when I want to open a file by using method "FileName", it takes some time to load file in editor, but in next times, load speed is very good.
You can even see this issue in your provided example.
Regards <3

**Comment by abbaye** [comment]
Humm normally it's take about 1-2 sec max at first load.

You load from SSD, IDE or network ?

At first time the control create all visible ibytecontrol at it take the most time of load. What is your PC ?

**Comment by dondrakon** [comment]
It takes about 1-2 sec on my PC too. Is it possible to speed it up? As a way - create all needed controls in another thread on loading form.

**Comment by abbaye** [comment]
It's possible to preload all at control creation. I can make it optional via a bill properties...

**Comment by abbaye** [comment]
Hi @PersianEngineer  abd @dondrakon  it's fixed now.

You can use AllowPreloadByteInEditor property for activate or not this capability. it's set to true by default.

Give me feedback please

**Comment by dondrakon** [comment]
Hi @abbaye 
"AllowPreloadByteInEditor = true" migrates the delay from open file event to load form event :(

**Comment by abbaye** [comment]
Haaa humm I will check this this afternoon :smile:

**Comment by abbaye** [comment]
But now your first load are very fast like you want ?

**Comment by dondrakon** [comment]
Yes, the first load of a file is very fast! But application load speed is decreased.

**Comment by abbaye** [comment]
Another possibility is to put the BuildDataLine methods Public and you can call it. When your app is loaded ?

**Comment by abbaye** [comment]
I think have a solution. I will test this night

**Comment by abbaye** [comment]
I think I can't do faster at this time. 😒

**Comment by dondrakon** [comment]
I think the best way is calling BuildDataLine method in a separate thread, but without refactoring it is not possible ;( Or optimize somehow this method. 
I will try to prepare a solution too.

**Comment by abbaye** [comment]
I will check this too

**Comment by abbaye** [comment]
do you have worked in this ? for me I dont have time right now :(

**Comment by dondrakon** [comment]
> 
> 
> do you have worked in this ? for me I dont have time right now :(

Sorry, but I don't have time too. I will try to work on this at this weekend.

**Comment by abbaye** [comment]
No sorry. Same like you the free time is rare :disappointed:
