### ISSUE TITLE
File handle not closed

### ISSUE THREAD

**Issue by korgak** [abbaye/WpfHexEditorControl#51]
## Expected Behavior
- File open (via FileName = FileA)
- Save file as FileB (via SubmitChanges(filename)
- Open file FileB, or any other file (via FileName = FileB)
- Open FileA 

## Actual Behavior
- File open (via FileName = FileA)
- Save file as FileB (via SubmitChanges(filename)
- Open file FileB, or any other file (via FileName = FileB)
- Open FileA throws error. File in use

## Steps to Reproduce the Problem

See above

**Comment by abbaye** [comment]
humm after 30min of testing I can't reproduce your bug...

Can you put the code you use ?

**Comment by korgak** [comment]
Thanks for testing it, I just created some simple code to test it.
FYI I am using Winforms with .net 4.5.1.

Also, with this code, If I want to save a file but I didn't make any changes, the saved file will be empty. Am I missing something here?

```
public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private const string BinaryFileFilter = @"All files (*.*)|*.*";

        private void btnLoadFile_Click(object sender, EventArgs e)
        {

            var dialog = new OpenFileDialog { Filter = BinaryFileFilter };
            dialog.ShowDialog();

            if (System.IO.File.Exists(dialog.FileName))
            {
                heWrittenData.FileName = dialog.FileName;
            }
        }

        private void btnSaveFile_Click(object sender, EventArgs e)
        {
            var fileDialog = new SaveFileDialog
            {
                Filter = BinaryFileFilter,
                Title = @"Save a binary file"
            };
            fileDialog.ShowDialog();

            if (fileDialog.FileName == "") return;

            heWrittenData.SubmitChanges(fileDialog.FileName, true);

            heWrittenData.FileName = fileDialog.FileName;
            heWrittenData.IsModified = false;
        }
    }
```

Many thanks for this awesome control :-)

**Comment by abbaye** [comment]
Cool thank you for code :) I will test with this night!

Thank for love my control :) do have put a start ? :smile:

PS: Check the lastest code with zoom in/out :grin:

**Comment by korgak** [comment]
Yes, now I did put a star :+1: 

How does the zoom work? And any luck with reproducing?

**Comment by abbaye** [comment]
Thank you for star :)

You can zoom with mouse wheel + Ctrl key or set in code ZoomScale property.

Get the lastest code on GitHub
