### ISSUE TITLE
FindFirst/Last/Next 

### ISSUE THREAD

**Issue by claudio-t** [abbaye/WpfHexEditorControl#52]
Hi abbaye,

Thank you for your great work, I am leveraging your library in a project that allows users to navigate huge binary file: not only works nice, but it is also intuitive and well written.

Nevertheless I have a few problems with the `Find` function family of the `HexEditor `control: when a `FindFirst/Next/Last` function is launched it won't terminate until all of the matchings are found instead of returning immediately. I investigated the code and this behaviour is dictated by the `ByteProvider.FindIndexOf` function [here](https://github.com/abbaye/WpfHexEditorControl/blob/2983da5be92a5fbcef8904ff43796411bb23d0f6/Sources/WpfHexaEditor.Shared/Core/Bytes/ByteProvider.cs#L1389) which keeps searching for all occurrences by design (causing a series of problems for big files a/o many matches).

May I help you with this improvement?

## Expected Behavior
`FindFirst/Last/Next` should return immediately after the given bytearray has been found.

## Actual Behavior
`FindFirst/Last/Next` returns after the whole file is searched for all matches

## Steps to Reproduce the Problem

  1. Invoke the aforementioned function anytime anywhere.

**Comment by abbaye** [comment]
Hi @claudio-t

I will check this to night :) 

Thank for support. If you like put a 🌟 on my project :)

I will come back soon as possible with the answer (I'm at work now)

Best regards

**Comment by abbaye** [comment]
I will update the FindIndexOf() method to be more efficient. :smiley:

**Comment by abbaye** [comment]
Hi @claudio-t 

Please get the last code and if you can test it. I think you should be happy 😄

**Comment by claudio-t** [comment]
Hi Derek, thank you for your immediate reponse! I am trying to build it with VS2017 with .NetFramework 4.7 but unfortunately compiler is failing because of the switch expression defined [here](https://github.com/abbaye/WpfHexEditorControl/blob/14092488a9ce3f93d7415953ed809988906802bc/Sources/WpfHexaEditor.Shared/Core/Bytes/ByteConverters.cs#L108). 
Do you have any suggestion to sidestep this inconvenient?

**Comment by abbaye** [comment]
Hi Claudio

Use Visual studio 2019 for compile this new switch

**Comment by claudio-t** [comment]
I will let you know in a while because at work I am stuck with 2017. I'll build it at home on my laptop :)

**Comment by abbaye** [comment]
Good thank you.

If you want put a 🌟 in my project : smile:

**Comment by claudio-t** [comment]
Hi Derek,

I've just managed to try it, but it seems not to work either using the dialog box or calling FindFirst directly (I see that you used an elgant yeld return statement but it doesn't do the trick).

**Comment by abbaye** [comment]
Humm normally it's work when you don't use the dialog box...

I will check this tonight. I think I have make a little bug in my change

**Comment by abbaye** [comment]
after checkup and tested and retested again and again... all finds and replace methods seem like to work fine.

how did you use it ? Please put somes code
