### ISSUE TITLE
binding errors in output window (version 1.9.1)

### ISSUE THREAD

**Issue by joern477** [abbaye/WpfHexEditorControl#54]
## Expected Behavior
No binding errors in output window

## Actual Behavior
Using wpfhexeditor control shows the following binding errors in output window of visual studio:

System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='WpfHexaEditor.HexEditor', AncestorLevel='1''. BindingExpression:Path=SelectionLine; DataItem=null; target element is 'Label' (Name=''); target property is 'Content' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='WpfHexaEditor.HexEditor', AncestorLevel='1''. BindingExpression:Path=SelectionLine; DataItem=null; target element is 'Label' (Name=''); target property is 'Content' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='WpfHexaEditor.HexEditor', AncestorLevel='1''. BindingExpression:Path=SelectionStart; DataItem=null; target element is 'Label' (Name=''); target property is 'Content' (type 'Object')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='WpfHexaEditor.HexEditor', AncestorLevel='1''. BindingExpression:Path=SelectionStart; DataItem=null; target element is 'Label' (Name=''); target property is 'Content' (type 'Object')

## Steps to Reproduce the Problem
1. Use nuget.org version 1.9.1
2. Add the HexEditorControl to your WPF GUI

**Comment by abbaye** [comment]
Hi joern477

Please use the lastest code on GitHub.

This nuget package is old.

Keep me informed if you have the same problem and I will check to fix it

**Comment by abbaye** [comment]
Hi @joern477 

Issue fixed. Download the lasted code on github for testing.

**Comment by joern477** [comment]
Hi @abbaye 

Tested your fix today. Binding errors are gone.

Thanks a lot for your super fast fix :-)

**Comment by abbaye** [comment]
Thank you ! If you want put a 🌟 on my project :)
