### ISSUE TITLE
Set correct version numbers in assemblys from nuget.org

### ISSUE THREAD

**Issue by joern477** [abbaye/WpfHexEditorControl#55]
## Expected Behavior
provided assembly's should contain the version number of the nuget package

## Actual Behavior
WPFHexaEditor.dll version information shows 1.0.0.0 for all versions from nuget.org

## Steps to Reproduce the Problem
View the version information of the assembly from explorer

**Comment by abbaye** [comment]
Yes ! I will do on next nuget release 

Thank for this info :)
