### ISSUE TITLE
add bindable command for HexEdit.SubmitChanges()

### ISSUE THREAD

**Issue by joern477** [abbaye/WpfHexEditorControl#56]
## Expected Behavior
It should be possible to bind a Command to HexEdit.SubmitChanges() from xaml file.
This way it would be possible to follow the MVVM pattern.

## Actual Behavior
Currently it has to be implemented in code behind file

**Comment by abbaye** [comment]
Yes it's possible and nice idea :smile:

I will work in this soon as possible.

**Comment by abbaye** [comment]
You can now use some commands with hexeditor

- RefreshView
- SubmitChanges

I will add another commands when I willl have the time 😄
