### ISSUE TITLE
this disable button click event

### ISSUE THREAD

**Issue by linxzhang** [abbaye/WpfHexEditorControl#57]
1. Windows 10, .net4.7.2.
2. C# WPF with Visual Studio 2019.
3.  below XMAL file:
     <StackPanel Orientation="Vertical">
          <Button x:Name="filebtn" Content="Button" HorizontalAlignment="Left" Click="click_handle"  Width="75"/>
                <control:HexEditor x:Name="HexEdit" Width="Auto" Height="Auto"/>
     </StackPanel>
4. no click event on the button.
5. remove HexEditor controller, button works OK.

**Comment by abbaye** [comment]
On file ?? in sample projet ?

**Comment by linxzhang** [comment]
I create a new project, XAML file is:
<StackPanel Orientation="Vertical">
                <Button x:Name="filebtn" Content="Button" HorizontalAlignment="Left"  Width="75"/>
                <control:HexEditor x:Name="HexEdit" Width="Auto" Height="Auto"/>
            </StackPanel>
and codes is:
            filebtn.Click += (s, e) => {
                var fileDialog = new OpenFileDialog();

                if (fileDialog.ShowDialog() != null && File.Exists(fileDialog.FileName))
                {
                    Application.Current.MainWindow.Cursor = Cursors.Wait;

                    HexEdit.FileName = fileDialog.FileName;

                    Application.Current.MainWindow.Cursor = null;
                }
            };
        }

but when i click the button, nothing happened. if i remove HexEditor, then it works on button.

**Comment by linxzhang** [comment]
<StackPanel Orientation="Vertical">
                <Button x:Name="filebtn" Content="Button"  />
                <control:HexEditor x:Name="HexEdit" Width="Auto" Height="Auto"/>
            </StackPanel>

**Comment by abbaye** [comment]
Do you have taken the latest code on github ?

**Comment by linxzhang** [comment]
it always remove the button line code when i submit this issue, again below is the XAML codes:
                <Button x:Name="filebtn" Content="Button" />
                <control:HexEditor x:Name="HexEdit" Width="Auto" Height="Auto"/>

**Comment by linxzhang** [comment]
yes, i just cloned the latest codes from here.

**Comment by abbaye** [comment]
do you have check the sample project ?

i will try your code right now 😄

**Comment by linxzhang** [comment]
sure.
i build the sample project and seems that it works ok. 
but i load file from menu, i just want to have a try through a button.

**Comment by abbaye** [comment]
it's work fine:

using Microsoft.Win32;
using System.IO;
using System.Windows;
using System.Windows.Input;

namespace WpfApp1
{

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            filebtn.Click += (s, e) =>
            {
                var fileDialog = new OpenFileDialog();

                if (fileDialog.ShowDialog() != null && File.Exists(fileDialog.FileName))
                {
                    Application.Current.MainWindow.Cursor = Cursors.Wait;

                    HexEdit.FileName = fileDialog.FileName;

                    Application.Current.MainWindow.Cursor = null;
                }
            };
        }
    }
}

**Comment by abbaye** [comment]
XAML:

<Window
    x:Class="WpfApp1.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:control="clr-namespace:WpfHexaEditor;assembly=WPFHexaEditor"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="clr-namespace:WpfApp1"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="MainWindow"
    Width="800"
    Height="450"
    mc:Ignorable="d">

    <Grid Margin="0,40,0,0">
        <control:HexEditor
            x:Name="HexEdit"
            Width="Auto"
            Height="Auto" />
        <Button
            x:Name="filebtn"
            Width="75"
            Margin="11,-34,0,0"
            HorizontalAlignment="Left"
            VerticalAlignment="Top"
            Content="Button" />
    </Grid>
</Window>

**Comment by linxzhang** [comment]
please try below codes:
   <Grid Margin="0,40,0,0">
        <StackPanel>
        <control:HexEditor
        x:Name="HexEdit"
        Width="Auto"
        Height="Auto" />

        </StackPanel>
        <StackPanel>
            <Button
        x:Name="filebtn"
        Width="75"
        Margin="11,-34,0,0"
        HorizontalAlignment="Left"
        VerticalAlignment="Top"
        Content="Button" />
        </StackPanel>
    </Grid>

**Comment by linxzhang** [comment]
yes, it works ok on your pasted codes. but it doesn't work within stackpanel.

**Comment by abbaye** [comment]
Try this 👍 

<StackPanel
            Width="75"
            Margin="11,-34,0,0"
            HorizontalAlignment="Left"
            VerticalAlignment="Top">
            <Button x:Name="filebtn" Content="Button" />
            
</StackPanel>

**Comment by abbaye** [comment]
If you like my project hit the ⭐ button please 😄

**Comment by linxzhang** [comment]
thanks a lot.
