### ISSUE TITLE
How to close the pop window "click to cancel the current job"

### ISSUE THREAD

**Issue by linxzhang** [abbaye/WpfHexEditorControl#59]
Hi,
i believe this is not a issue, but i don't know how to close the window "click to cancel the current job" after click the "save" menu. in fact it's below line code:
            HexEdit.SubmitChanges();
after this, it cannot edit file too.

does it possible to edit after clicking "save"? i'd like to have a tutorial document on how to use this WPF controller in more detail.

thanks a lot.

**Comment by abbaye** [comment]
Hi @linxzhang 

It's not a pupup but a button. It will appear only on long task. If you want cancel you have just to click on.

Yes it's possible to edit after save the file.

Do you have try the sample project ?? :smile:

**Comment by linxzhang** [comment]
Dear Sir,

thanks for your reply!

Well, i'm just using the sample project, the popup button will not disappear after click the "save" menu. and i opened a 20k size binary file, it's samll enough so it'll not take a long time to complete this "saving task".

sure, i also clicked the popup button, but nothing happened.

please see below picture:

![图片](https://user-images.githubusercontent.com/7834208/71220002-fa547580-2301-11ea-9168-a5676093ebce.png)

thanks a lot.

**Comment by abbaye** [comment]
hooo I think it's a little bug.

**Comment by abbaye** [comment]
Corrected
