### ISSUE TITLE
Seeing incredibly bad performance on .NET Core 3.1

### ISSUE THREAD

**Issue by goaaats** [abbaye/WpfHexEditorControl#61]
**Describe the bug**
The HexEditor control causes very high refresh times in my .NET Core 3.1 app, with up to 500ms for a single refresh increasing with time.

**To Reproduce**
1. Create a new .NET Core 3.1 WPF application
2. Include WpfHexaEditor in your project
3. Create the following XAML window:

```xaml
<Window x:Class="namespace:TestApp.TestWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TestApp"
        xmlns:wpfHexaEditor="clr-namespace:WpfHexaEditor;assembly=WPFHexaEditor"
        mc:Ignorable="d">
    <Grid>
        <StackPanel Margin="5,5,5,5">
            <wpfHexaEditor:HexEditor x:Name="Editor"/>
        </StackPanel>
    </Grid>
</Window>
```

4. Use the following constructor for the window:

```cs
			public TestWindow()
        {
            InitializeComponent();
            
            var stream = new MemoryStream(new byte[] { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09 });
            MessageHexEditor.Stream = stream;
        }
```

5. Observe that the app is very slow, and will progressively get slower with the log showing output like this:
```
REFRESH TIME: 375 ms
REFRESH TIME: 411 ms
REFRESH TIME: 396 ms
REFRESH TIME: 381 ms
REFRESH TIME: 419 ms
```

**Expected behavior**
The app should be fast.

**Screenshots**
When adding a hex edit control, the app is slow and will become unusable.
![image](https://user-images.githubusercontent.com/16760685/78452790-5b913080-76c8-11ea-912e-429c76311543.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Framework: .NET Core 3.1
 - Package Version: 2.0.2

Is this an issue with my usage of the control?
Is .NET Core 3.1 not supported yet?

This issue also occurs on .NET Core 3.0 and in Debug and Release builds.

**Comment by abbaye** [comment]
I will check this tomorrow :)

Thank for submitting this issue

**Comment by abbaye** [comment]
I will check this tomorrow :)

Normally the refresh time is 4-9ms

Thank for submitting this issue

**Comment by abbaye** [comment]
Hi @goaaats 

Hi have made some test over netcore3.1 and my refresh time is like 👍 

REFRESH TIME: 8 ms
REFRESH TIME: 8 ms
REFRESH TIME: 17 ms
REFRESH TIME: 8 ms
REFRESH TIME: 8 ms
REFRESH TIME: 8 ms

What is your configuration ? Do you have tested with framework 4.7 ? (for comparaison)

**Comment by Skyppid** [comment]
Can confirm, I added this into a relatively raw application (only one grid and that control next to it) and I my application hangs for about 1+ seconds when I resize or load the file (450kb binary file). Scrolling the view is also quite laggy.

Running on Core 3.1 as well.

**Comment by abbaye** [comment]
😬😬 I will check soon. Thank you 😊

**Comment by Skyppid** [comment]
To help you a little further, I noticed the following things:
* It takes a very long time to maximize a window with this control
* When resizing manually by cursor there's different states where it performs better or worse (seems like it's always an "address chunk" where it becomes more laggy wheras when the next becomes visible it renders a little smoother whereas it performed worst when the text representation on the right and the scrollbar was fully visible)

If I got time I might do a profiling session with Visual Studio to analyze the rendering.
