### ISSUE TITLE
WinUI 3.0 Support

### ISSUE THREAD

**Issue by shaggygi** [abbaye/WpfHexEditorControl#62]
Understanding it is still in preview and not to be released until November 2020 with .NET 5, but wondering if there were plans to create a WinUI version for HexEditorControl?  BTW... nice control 👍

**Comment by abbaye** [comment]
I will check this when is possible but it's a nice idea :smile:

**Comment by shaggygi** [comment]
@abbaye thx 👍

**Comment by abbaye** [comment]
Your welcome !
