### ISSUE TITLE
Memory leak when using HexEditor dynamically

### ISSUE THREAD

**Issue by distraktd** [abbaye/WpfHexEditorControl#64]
**Describe the bug**
I have a tabbed application where people can open files and the UI is dynamically generated so on open I create a HexEditor like:

HexEditor hexEditor = new HexEditor();
hexEditor.FileName = fileName;

Which gets added to a DockPanel. When a tab is closed I call

hexEditor.CloseProvider();

Which I am under the impression should cleanup everything associated with the HexEditor. However when using a profiling tool like ReSharper there is about 30-40mb of memory that remains in use even after forcing GC multiple times. Now the majority of that is under the System namespace (32 ish MB) but there is about 400k under WpfHexaEditor which I'm wondering might be the cause? Or is this a problem with WPF? Or have I totally misunderstood how to free a HexEditor?

I tried opening and closing other files in case it was some kind of optimisation that wasn't being GC'd but every creation and destruction of a HExEditor grew the memory by 30-40mb.

I even left the application running for 10 minutes then forced a GC again but no dice.

**To Reproduce**
Create a HexEditor as above, render it i.e. view it, then call CloseProvider and allow the UI container to fall  out of scope and be collected.

**Expected behavior**
Memory associated to HexEditor to be cleaned up.

**Desktop (please complete the following information):**
 Windows 10 1909 .Net Framework 4.7.2

If I've incorrectly used the HexEditor control then please correct me and close the ticket :)

**Comment by dondrakon** [comment]
Did you try to call hexEditor.Dispose() method on closing your tab?

**Comment by distraktd** [comment]
I modified my code so that when the tab is being closed i do:

hexEditor.CloseProvider();
hexEditor.Dispose();

(Previously I had only done CloseProvider())

Then using dotMemory with a force GC (spamming it multiple times) the memory usage still doesn't drop.

**Comment by abbaye** [comment]
Normally the control use 25-150 mb of memory.  

it can use little more depending of the number of byteperline and row are loaded. 
i'm using "Framework element" to build the visual. I think I can't go more deep in WPF element.
