### ISSUE TITLE
[Question] How to disable highlighting similar values

### ISSUE THREAD

**Issue by shaggygi** [abbaye/WpfHexEditorControl#66]
When I select a value in a cell, 0x00 for example, all other cells that contain 0x00 are highlighted.  This can be confusing and hard to tell which cell(s) are really selected.  Is there a property to turn this off?

Thanks in advance.

**Comment by abbaye** [comment]
Hi!

You can disable via a "Is" property.

I will give tomorrow the exact name of property tomorrow.

**Comment by abbaye** [comment]
Hi @shaggygi 

Use the property : AllowAutoHighLightSelectionByte = false

**Comment by shaggygi** [comment]
@abbaye That's what I needed.  Thanks a bunch!
