### ISSUE TITLE
problem header location after changing datastringvisualization property

### ISSUE THREAD

**Issue by ehsan69h** [abbaye/WpfHexEditorControl#67]
after open file in hex editor. set new setting changing data string visual from hexdecimal to decimal.
but header showing incorrect width like this image

![image](https://user-images.githubusercontent.com/46125133/93085814-67d3dd80-f6ab-11ea-94ac-63b439182405.png)

**Comment by abbaye** [comment]
Hi

You can check the header visual via a property.

I'm not front my computer for give to you the exact name 😅 I have a white space in my memory 😅

I will check this at the end of the day and I will come back

**Comment by ehsan69h** [comment]
Hi
I can't find property for header visual config!😕

**Comment by abbaye** [comment]
Hi

I have juste checked my code and you should use the property

DataStringVisual="Decimal"

**Comment by ehsan69h** [comment]
HI
yes, I used that (see in the image on the first comment). but the header of the buffer section showing on previous format (the first comment image)

**Comment by abbaye** [comment]
1- Check your code with a break point and go step by step in DataVisualString to find what is bug

2 - Change the property in your call et launch your project (just for test if this way work good)

**Comment by ehsan69h** [comment]
1- I used breakpoint and find problem on condition of For statement
![image](https://user-images.githubusercontent.com/46125133/93736585-ae669200-fbed-11ea-884b-b7ab8a1d3534.png)

2- yes, when i set this at launch, work cerectly

**Comment by abbaye** [comment]
Ok the bug in when the control is already loaded

I will put an update soins as possible for correct this

Thank you

**Comment by abbaye** [comment]
It's corrected. Get the last code on github
