### ISSUE TITLE
[Question] File appears to be locked while using with control

### ISSUE THREAD

**Issue by shaggygi** [abbaye/WpfHexEditorControl#68]
After setting the WpfHexEditorControl FileName property, I get a "file being used by another process" when trying to read the file contents.  Is there a way to load the data once and release the file so it can be viewed by the control and read elsewhere at the same time?

Thanks in advance for any help.

**Comment by abbaye** [comment]
The Read only mode need to set to false.

You can't modify a file in decimal mode for now but just in Hex

**Comment by abbaye** [comment]
Copy you file in another folder and try to open.

**Comment by shaggygi** [comment]
Looks like I get same error when setting ReadOnlyMode to true or false.  I can't copy file to another location based on my scenario.  I'm thinking I can perform a different order or use CloseProvider() to get around this.  Thx

**Comment by abbaye** [comment]
are you sure than your file are not locked by another process ?

The control need the exclusive acces to the file.
