### ISSUE TITLE
bytes tooltip don't update after change byte value

### ISSUE THREAD

**Issue by ehsan69h** [abbaye/WpfHexEditorControl#72]
after changing the value of byte by the user, tooltip data don't be updated and show old data.

**Comment by abbaye** [comment]
Yes it's a little bug



Le lun. 28 sept. 2020 08 h 37, ehsan haghani <notifications@github.com> a
écrit :

**Comment by ehsan69h** [comment]
are you know the problem is where?
can I fix this?

**Comment by abbaye** [comment]
You can fix this if you want.

I have just not the time right now 😔

Le lun. 28 sept. 2020 09 h 22, ehsan haghani <notifications@github.com> a
écrit :
