### ISSUE TITLE
ReadOnly is cropped

### ISSUE THREAD

**Issue by raffaeler** [abbaye/WpfHexEditorControl#74]
**Describe the bug**
With these properties, the "Readonly" text in the bottom-right part of the window is cropped.
```
<hex:HexEditor Width="Auto" Height="Auto" x:Name="hexEditor" ByteSpacerPositioning="Both"
               FontSize="16" ReadOnlyMode="True" />
```

![image](https://user-images.githubusercontent.com/5183152/95626669-079e4480-0a7b-11eb-9417-68cb2d22e72b.png)

**To Reproduce**
Set the properties as shown above and run with any data.

**Expected behavior**
The text should not be cropped.

**Desktop (please complete the following information):**
 - OS: Windows 10 - 2004
 - .NET Core 3.1

**Comment by abbaye** [comment]
Thank for this.

I will correct that this weekend ☺️

**Comment by abbaye** [comment]
Corrected 😄

**Comment by raffaeler** [comment]
Would you mind to publish a nuget update?

**Comment by abbaye** [comment]
Yes i will right now

**Comment by abbaye** [comment]
Are you testing ?

**Comment by raffaeler** [comment]
Sorry, I could not make a test before. The problem is still there with version 2.0.3:
![image](https://user-images.githubusercontent.com/5183152/95713929-ad160b80-0c67-11eb-9f8d-2eaa0903b727.png)
I would suggest you to use a StackPanel aligned on the right. My guess is that content alignment to center is causing the issue.

thanks

**Comment by abbaye** [comment]
Hummm it's work fine on my computer. I will correct this with a stack panel 🙂

**Comment by raffaeler** [comment]
I have no special settings (96DPI, 1920x1080 even if my monitors are 4K capable.

**Comment by raffaeler** [comment]
I added a link to your repo from mine :)
https://github.com/raffaeler/PowerDiagnostics

**Comment by abbaye** [comment]
Thank you

I will correct this issues this weekend

**Comment by abbaye** [comment]
I need to complete the pull request #78 before correct this because it's affect this file

**Comment by abbaye** [comment]
@raffaeler can you test with the lastest code ?

**Comment by abbaye** [comment]
Hi @raffaeler I have put an update of the nuggets package.

**Comment by raffaeler** [comment]
Sorry for the delay, but this has been a tough week.
Your fix is working good. There is only a small cosmetic issue when the control is resized too small:
![image](https://user-images.githubusercontent.com/5183152/99066317-119af200-25a9-11eb-9884-665dcfbe8c40.png)

I would suggest to entirely remove "Readonly" in this case, but this is up to you :)

**Comment by abbaye** [comment]
I will correct this soon! Thank you mister

**Comment by abbaye** [comment]
I think I will change this label by another thing... Comeback soon

**Comment by raffaeler** [comment]
Sure, no problem.
BTW you can notice also the bottom alignment of "Readonly" being different than the other labels.
