### ISSUE TITLE
Read only label is not affected by status bar visibility

### ISSUE THREAD

**Issue by Filipsi** [abbaye/WpfHexEditorControl#79]
**Describe the bug**
Label indicating that editor is in "read only" mode is not affected by status bar visibility and creates empty space if shown.

**To Reproduce**
1. Set StatusBarVisibility property to "Collapsed"
2. Set ReadOnlyMode property to "True"

**Expected behavior**
Currently, the "read only" label is not part of the status bar.
In my opinion, this is incorrect since read only mode is a "status" of the editor.
It would be helpful to move it to the status bar, since it would allow it to be hidden.
As a side effect, it would also probably resolve positioning issues simar to ones described in issue #74.

Alternatively, if it's not possible to change editor layout, it would be helpful to at last have property to control it's visibility.

**Screenshots**
Read only mode disabled with status bar collapsed 
![example1](https://user-images.githubusercontent.com/5103404/98546792-87484a80-2297-11eb-8f76-5821c46fa2b7.png)

Read only mode enabled with status bar collapsed
![example2](https://user-images.githubusercontent.com/5103404/98546112-bf02c280-2296-11eb-90a1-13e8ff432e56.png)

**Desktop:**
 - OS: Windows 10
 - Platform: .NET Core 3.1

**Comment by abbaye** [comment]
Oupssi will correct this :sweat_smile:
