### ISSUE TITLE
Button allowing to cancel long running process stays open after saving

### ISSUE THREAD

**Issue by Filipsi** [abbaye/WpfHexEditorControl#80]
**Describe the bug**
After submitting changes, the button allowing to cancel long running process remains visible and can't be closed.

**To Reproduce**
1. Start sample application
2. Open a file in hex editor
3. Perform changes
4. Save the file

**Expected behavior**
The button allowing to cancel long running process will be hidden when changes are finished saving.

**Screenshots**
![example](https://user-images.githubusercontent.com/5103404/98553069-7e5b7700-229f-11eb-9013-4a8dcda19426.png)

**Desktop**
    OS: Windows 10
    Platform: .NET Core 3.1

**Comment by abbaye** [comment]
I think your pull request #81 fix this. I will push at end of day
