### ISSUE TITLE
Editor stays editable after opening a locked file in read only mode 

### ISSUE THREAD

**Issue by Filipsi** [abbaye/WpfHexEditorControl#83]
**Describe the bug**
When you open a locked file and accept the dialog for opening it in read only mode, the editor stays editable.
But the internal byte provider itself switches to read only mode. This results in confusing behavior.
When you attempt to save changes, it looks like the changes are saved, but they are not.

**To Reproduce**
1. Start sample application
2. Open locked file
3. Accept dialog for opening the file in read only mode
4. Make any changes
5. Save the file

**Expected behavior**
After opening locked file, the editor switches to read only mode and prevents modifications.

**Desktop**
OS: Windows 10
Platform: .NET Core 3.1

**Comment by abbaye** [comment]
I check this at end of day :) 

Thank you @Filipsi

**Comment by abbaye** [comment]
oupss i< created a bug...

**Comment by abbaye** [comment]
I have another bug with ReadOnly, I will check this weekend
