### ISSUE TITLE
Context menu options that are modifying bytes can be used in read only mode

### ISSUE THREAD

**Issue by Filipsi** [abbaye/WpfHexEditorControl#84]
**Describe the bug**
It is possible to use "Paste without inserting", "Fill selection with bytes" and "Replace byte in selection" context menu options when the editor is in read only mode.

**To Reproduce**
1. Start sample application
2. Open a file
3. Enable read only mode
4. Try using "Paste without inserting", "Fill selection with bytes" and "Replace byte in selection" options from context menu

**Expected behavior**
Context menu options that are modifying bytes should be ether disabled or hidden when editor is in read only mode.

**Screenshots**
![example](https://user-images.githubusercontent.com/5103404/98688726-736e1880-236b-11eb-8f6f-cc144c3baa73.png)

**Desktop**
OS: Windows 10
Platform: .NET Core 3.1

**Comment by abbaye** [comment]
Thank you :) 

I will correct this at end of day

**Comment by abbaye** [comment]
I have intagrate a check flag in all editable method and disabled editable menu... 😄
