### ISSUE TITLE
AvalonDock and HexEditor don't play nicely with eachother

### ISSUE THREAD

**Issue by LennardF1989** [abbaye/WpfHexEditorControl#86]
Some sort of weird WPF bug is happening when this Hex Editor and AvalonDock are used together. When you drag a Document-window with a Hex Editor to a different dock, an exception occurs during de GridResizing event.

```
System.NullReferenceException
  HResult=0x80004003
  Message=De objectverwijzing is niet op een exemplaar van een object ingesteld.
  Source=PresentationCore
  StackTrace:
....
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WatchDogsLegion.App.Main()
```

Not sure if related, the Hex Editor also significantly slows down the application when it is resizing. Looking at the code, a lot is happening during a resize.

**Comment by abbaye** [comment]
Hello Lennard,

I have never tested the HexEditor in  Avalon dock panel.😅 But I know good Avalon dock 💪

I will check this and try to find a way  for it's work fine.😁

Sorry for inconvenient 😔

**Comment by abbaye** [comment]
I will try to disable the resize and reactivate it after the dock are completed...

**Comment by LennardF1989** [comment]
No problem, I'm very glad you have this thing at all! Saves me a lot of trouble having to make it myself :)

Yea, I was looking for something like a "Pause" and "Unpause" when doing things like this. Perhaps its as easy as that solution?

**Comment by abbaye** [comment]
It's easy to implement something like:

Hexcontrol.DisableAutoRefresh()
//Code
Hexcontrol.EnableAutoRefresh()
Hexcontrol.RefreshControl()

**Comment by abbaye** [comment]
I will implement today. I think of you have this bug, another one can have also ;)

**Comment by abbaye** [comment]
I have added the public property IsAutoRefreshOnResize 

Test like this:

HexEditor.IsAutoRefreshOnResize = False;
// Execute code that does not need to be refreshed
HexEditor.IsAutoRefreshOnResize = True;
HexEditor.RefreshView(true);

I hope it's will work

**Comment by LennardF1989** [comment]
This works, I however am having trouble figuring out what the right events would be to either enable/disable it. I was very certain there would be something like a "start docking" and "end docking" event, but I can't find it to properly test this :/

I can confirm however that pausing it immediately and then dragging the document around is now just as fast as any other screen, so the whole RefreshView constantly kicking off is VERY heavy.

**Comment by abbaye** [comment]
I will test in Avalon Dock today and I will come back with a solution

Thank for you testing

**Comment by abbaye** [comment]
I @LennardF1989 

Get the last code and launch the AvalonDock sample projet (.Net 4.7)

it's work fine for me... I hope will be ok for you
