### ISSUE TITLE
Delay when maximizing on .NET 5

### ISSUE THREAD

**Issue by binarycow** [abbaye/WpfHexEditorControl#90]
**Describe the bug**
Delay when maximizing on .NET 5

**Edit:** Also happens when zooming in/out with mouse wheel

**To Reproduce**
1. Load 16MB file
2. Maximize window - Delay of about 3 seconds before window actually resizes

**Expected behavior**
1. Window should resize instantly (or close to it)

Versions
- Win10
- .NET 5
- Nuget package 2.1.2

```
<Window x:Class="HexEditor.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:HexEditor" 
        xmlns:control="clr-namespace:WpfHexaEditor;assembly=WPFHexaEditor"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <control:HexEditor FileName="{Binding Filename}" />
    </Grid>
</Window>
```

**Comment by abbaye** [comment]
Thank for reports,

I have a solution. I will implement today if I have the time :)

Thank for reporting

**Comment by abbaye** [comment]
Fixed :)
 
Get the last code and set the control property :

PreloadByteInEditorMode = PreloadByteInEditor.MaxScreenVisibleLine.

by default the property is set to PreloadByteInEditor.None

Please give me a feedback

**Comment by binarycow** [comment]
@abbaye - That's much faster.

Note:  It's quite slow for the initial load.  16 MB file.  Like, 5-10 seconds.

**Comment by abbaye** [comment]
The file is not long to load but the all ByteControl at first time.

You can select the preload mode via the property PreloadByteInEditor :)

**Comment by binarycow** [comment]
So,

`PreloadByteInEditor.MaxScreenVisibleLine` fixes the screen maximizing delay

What would be the best value to use to fix the screen maximizing delay, but also won't take too long for initial load?

**Comment by abbaye** [comment]
MaxScreenVisibleLine is the most appropriate but it's have a cost on the first load only.

I will add another value in PreLoadByteInaeditor... I will come back before tomorrow

**Comment by binarycow** [comment]
👍 Thanks for the help!

**Comment by abbaye** [comment]
Thank to you ! It's with come back issues that I can optimize the control :)

**Comment by abbaye** [comment]
Give me a feedback when possible

please test the new MaxStreenVisibileLineAtDataLoad
