### ISSUE TITLE
How can i disable Virtualization

### ISSUE THREAD

**Issue by gggEddy** [abbaye/WpfHexEditorControl#91]
![1](https://user-images.githubusercontent.com/18212760/102572725-ca63cc00-4127-11eb-9975-4f24dda69c86.gif)

**Comment by abbaye** [comment]
Just for sure, you have created a lot of hexeditor in. A stack panel and when you move it the data is not refresh ?

**Comment by gggEddy** [comment]
> Just for sure, you have created a lot of hexeditor in. A stack panel and when you move it the data is not refresh ?

i create in the GridControl(Devxpress) , in DataGrid and listView there are memory leaks

**Comment by abbaye** [comment]
Can you put a sample of your code? It will be help me to understand what going wrong

**Comment by gggEddy** [comment]
<ListView ItemsSource="{Binding TestDataList}" VirtualizingPanel.IsVirtualizing="False">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="20"/>
                            <ColumnDefinition Width="*"/>
                        </Grid.ColumnDefinitions>
                        <TextBlock Grid.Column="0" Text="{Binding Index}"/>
                        <control:HexEditor Grid.Column="1" Stream="{Binding ByteStream}"/>
                    </Grid>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>

![3](https://user-images.githubusercontent.com/18212760/102691118-17899000-4245-11eb-93bf-13730ee51fbf.png)

**Comment by abbaye** [comment]
Unfortunly, I think the hexeditor is not adapted to be used like this.

Find another wait for dont load an hexeditor for all your ByteStream.

Check CurrentState property in the C# sampling on github

**Comment by gggEddy** [comment]
> Unfortunly, I think the hexeditor is not adapted to be used like this.
> 
> Find another way for not loading an hexeditor for all your ByteStream.
> 
> Check CurrentState property in the C# sampling on github.
> 
> //Current state sample using with Tabcontrol...
> //you can use with another stream than file. This sample code use only one hexeditor but can be used with 100 files if you want.
> 
> ```
>     private void FileTab_SelectionChanged(object sender, SelectionChangedEventArgs e)
>     {
>         if (!(sender is TabControl tc)) return;
>         if (!(tc.SelectedValue is TabItem ti)) return;
> 
>         //Set the tag of last selected ta to currentstate
>         if (e.RemovedItems.Count > 0 && e.RemovedItems[0] is TabItem lastSelectedTabItem)
>             lastSelectedTabItem.Tag = HexEdit.CurrentState;
> 
>         //Change loaded file and update the current state
>         var filename = ti.ToolTip.ToString();
>         if (!File.Exists(filename)) return;
> 
>         HexEdit.FileName = filename;
> 
>         //Setstate 
>         if (ti.Tag is XDocument doc)
>             HexEdit.CurrentState = doc;
>     }
> ```

Okay, but it's not for me. thanks anyway.
