### ISSUE TITLE
Can't Use Controls With ElementHost in Windows Forms

### ISSUE THREAD

**Issue by vector-man** [abbaye/WpfHexEditorControl#97]
## Expected Behavior
In Windows Forms, using the designer, setting an ElementHost's hosted content in Windows Forms should work.

## Actual Behavior
I get an error message "An error occurred trying to create an object of type "WpfHexaEditor.HexBox". Make sure the type has a default constructor" I get a similar error for the HexEditor as well.

## Steps to Reproduce the Problem

  1. Create a Windows Forms Project
  2. Add a ElementHost control to the form
  3. Set the hosted content to either of your hex controls.

**Comment by abbaye** [comment]
Are you tested the winform sample ?

**Comment by abbaye** [comment]
I never tested the Hexbox in elementhost I will check this

But normally the hexeditor work good in the sample

**Comment by vector-man** [comment]
Oh, I wasn't aware that you could use the control in Windows Forms without ElementHost (since it was a WPF control, I thought it was required.) I'll have to try that out and get back to you. Thanks!

**Comment by abbaye** [comment]
Yes it's required the elements host in winform

I have tested hexeditor but not Hexbox

**Comment by sherrygopal** [comment]
I am not sure if this is bug. But I am facing the same issue like the OP.
If you add manually WpfHexEditor as a child to in ElementHost in code view it works.

You cannot add from Form design if you try it generates the same error.

Initially I thought it is my project but later I tried in WpfHexEditor.Sample.WinForm as well.
If you make any change in Sample file form (MainForm.cs) it generates error for null.
`// elementHost
 // 
this.elementHost.Location = new System.Drawing.Point(0, 110);
this.elementHost.Name = "elementHost";
this.elementHost.Size = new System.Drawing.Size(504, 302);
this.elementHost.TabIndex = 3;
this.elementHost.Text = "elementHost";
this.elementHost.Child = null;`
The last line needs attention if you change it back to `this.elementHostChild = this.hexEditor` it works.

Thank you for your amazing work, impressive.

**Comment by abbaye** [comment]
Hi @sherrygopal !

I will try it right now.  I have make juste somes test over winform but it's possible that the control have somes bug whiten in.

Thank for your good word! I.make this project for fun. It's you want put a star ⭐ 

Thank you

**Comment by vector-man** [comment]
The error implies that adding a default constructor to your control would fix it. I'm not sure if there's anything else involved, but that may be the issue. I didn't used to have the problem on older versions of your control, so it may be a new bug.

**Comment by abbaye** [comment]
I will check this tomorrow !

Thank my friend.
