### ISSUE TITLE
Drag and drop filename!

### ISSUE THREAD

**Issue by aliakbari76** [abbaye/WpfHexEditorControl#98]
## Expected Behavior
create a tab with filename after drag and dropping file in editor!

## Actual Behavior
it's not making a new tab!
if editor isclear it just load without tab and if some file is open it just change the bufffer with the previous file name!

**Comment by abbaye** [comment]
The editor will never create a new tab in the sample.

The drag and drop filename or text will work only in the current instance.

**Comment by abbaye** [comment]
But I can modify the sample to do that... It's not impossible 😀

**Comment by aliakbari76** [comment]
i handeled it, but thanks!
